### PR TITLE
Fix errors on #16

### PR DESCRIPTION
**Pull request by cmdcolin**
With regards for #16 I found a couple of methods that can be used for fixing the issues that I saw on Chrome.
- Changes include using getAttribute for a lot of things instead of accessing them directly (originally I was tipped off when the "dataset" attributes were null, but it seemed a lot of things on Chrome needed getAttribute)
- Uses the deltaY instead of windowDeltaY for scrolling which fixes zoom on firefox
- Adds a note to use Command+Ctrl for scroll on Mac

### CODE REVIEW

**Comment by cmdcolin** [comment]
http://cmdcolin.github.io/flamegraph/web/

**Comment by fdegiuli** [comment]
👍

**Comment by cmdcolin** [comment]
It appears the chrome  changed the ".cpuprofile" format so even this doesn't work anymore...I can compare it and get ".cpuprofile" from an old version of chromium and confirm the change...I don't know if others like nodejs also use cpuprofile format or if they have changed as well(?)

**Comment by thlorenz** [comment]
@cmdcolin also noticed that the format changed .. working on trying to fix things.
Will have to update [cpuprofilify](https://github.com/thlorenz/cpuprofilify/) as well so it generates cpu profiles the same way that chrome does now.
Node.js uses v8-profiler which [calls into v8](https://github.com/node-inspector/v8-profiler/blob/master/src/cpu_profiler.cc) to get the cpu profile, so here it depends on the v8 version that's bundled with the Node.js version you're using WRT compatibility.

I'll try to change things in a way that things work for both versions of the format.
It seems like DevTools does the same, i.e. you can still load cpu profiles of the old format (and the new one of course), but when saving one you recorded it has the new format.

**Comment by thlorenz** [comment]
Dove into this a bit @cmdcolin.
The affected cpu profiles that have the new format are only the ones created and saved from Chrome.
The change is somewhat dramatic and I created a [separate issue](https://github.com/thlorenz/flamegraph/issues/21) for adapting the processor to consume it.

However for now everything still works with any profile produced either via `v8-profiler` or `cpuprofilify`. For me personally that part is most important and I make a note in the readme about the broken part.

In the meantime merged your PR 2a51acf since those improvements are awesome nevertheless :)
Thanks.

**Pull request closed without merging**
